### ISSUE TITLE
Question: ProseMirror dispatch decorations

### ISSUE THREAD

**Issue by whawker** [smc/mlmorph#15]
Hi, I've come across this repo via the ProseMirror forum, I have a similar use case as your spellcheck API (a thesaurus use case).

I was curious about how the spellcheck plugin dispatches transactions.

I notice how it dispatches a transaction [inside the descendants callback](https://github.com/smc/mlmorph/blob/master/docs/components/editor/SpellcheckerExtension.js#L89) which results in a transaction for each descendant.

Is this done as a performance optimisation? Drawing the decorations line by line, rather than doing one dispatch, _after_ the descendants function?

This isn't meant as a critism or anything like that, genuinely interested in best practices for these use cases!

**Comment by santhoshtr** [comment]
Thanks for the question. Yes, I did this intentionally, but not for any performance optimization(I have not checked if there is a problem with performance by doing like this). This was just a lazy attempt to avoid waiting for all promises(`checknode` is async) to finish, aggregate all problems. I thought if I just dispatch the transaction, once the node is checked is more easier and may be faster response to user. By the way, nodes are not necessarily lines, they are probably paragraphs, or inline markup elements.

**Comment by whawker** [comment]
That's interesting, thank you very much.

Have you consider using [`getChangedRanges`](https://github.com/ueberdosis/tiptap/blob/4c9460507110fd08e405af39b8c50fb302cd4d8c/packages/core/src/helpers/getChangedRanges.ts#L35) to execute the plugin only on the changed nodes?

**Comment by santhoshtr** [comment]
> Have you consider using [`getChangedRanges`](https://github.com/ueberdosis/tiptap/blob/4c9460507110fd08e405af39b8c50fb302cd4d8c/packages/core/src/helpers/getChangedRanges.ts#L35) to execute the plugin only on the changed nodes?

No. I was not aware of this. Thanks for the link. 

There are many optimization ideas we can apply for spellcheck or similar usecases. For example, keeping the dictionary of words and the corresponding API result(spellcheck result) and checking the word in that one before an API request, so that we can fast lookups. That would be independent of transactions and text changes. Imagine a paragraph is cut(Say Transaction-12) and then pasted somewhere else as Transaction-42. In such case, a content diff from previous transactions wont save API cost, but the cached results would help. Am I right?

For my usecase, I was not interested in optimizing this editor usage since my purpose is just demo the spellcheck API. Improving the spellcheck and underlying morphology anayser is where I would spend time. But definitely the spellchecker won't be useful if there is no good text editor :-)

**Comment by whawker** [comment]
Thanks so much for your insights! Very helpful and much appreciated!
